// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeSQjDtYAMGEPgzVp5WWuk285AB-Bt5Rw',
    appId: '1:221451186028:web:dc8a5d5880f78898280d49',
    messagingSenderId: '221451186028',
    projectId: 'role-based-access-practice',
    authDomain: 'role-based-access-practice.firebaseapp.com',
    storageBucket: 'role-based-access-practice.firebasestorage.app',
    measurementId: 'G-PQCXTTV7Q9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARqTgWYsczYxDChQfgfHE-yXv7xS79SMA',
    appId: '1:221451186028:android:1ab68175f382d756280d49',
    messagingSenderId: '221451186028',
    projectId: 'role-based-access-practice',
    storageBucket: 'role-based-access-practice.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClafgIgIzvMp9_0J_0smKla9CvhLPeVZg',
    appId: '1:221451186028:ios:e1d1e0c98e529602280d49',
    messagingSenderId: '221451186028',
    projectId: 'role-based-access-practice',
    storageBucket: 'role-based-access-practice.firebasestorage.app',
    iosBundleId: 'com.example.rbacApp',
  );
}
